// schemas/objects/module.ts
import {defineType} from 'sanity'

export default defineType({
  name: 'moduleBuilder',
  title: 'Page Modules',
  type: 'array',
  of: [
    {type: 'heroModule'},
    {type: 'homeBannerModule'},
    {type: 'ctaBannerModule'},
    {type: 'faqModule'},
    {type: 'featuredCardsModule'},
    {type: 'imageGalleryModule'},
    {type: 'logosModule'},
    {type: 'richTextModule'},
    {type: 'statsModule'},
    {type: 'testimonialModule'},
    {type: 'twoColumnModule'},
    {type: 'readerFavourites'},
    {type: 'activitiesModule'},
    {type: 'nestedFaqModule'},
    {type: 'categoryHighlightModule'},
    {type: 'currentIssueModule'},
    {type: 'realEstateModule'},
    {type: 'subscriptionBannerModule'},
    {type: 'classicsModule'},
    {type: 'galleryModule'},
    {type: 'simpleBanner'},
    {type: 'teamMembers'},
    {type: 'bannerWithBottomContent'},
    {type: 'introWithImages'},
    {type: 'coverageOverview'},
    {type: 'miniGallery'},
    {type: 'ctaCardsSection'},
    {type: 'formContent'},
  ],
})
