import {
  HomeBanner,
  RichText,
  ReaderFavourites,
  ActivitiesModule,
  Subscribe,
  RealEstate,
  TravelGuides,
  Gallery,
  TwoColumnImageContent,
  CurrentIssue,
  NestedFaqModule,
  SimpleBanner,
  BannerWithBottomContent,
  IntroWithImages,
  CoverageOverview,
  MiniGallery,
  TeamMembers,
  CtaCardSection,
  DynamicForm,
  ContactUsComponent,
  ShopifyProductListing,
} from "@/components";

export const moduleMapper: Record<string, React.FC<any>> = {
  homeBannerModule: HomeBanner,
  richTextModule: RichText,
  readerFavourites: ReaderFavourites,
  activitiesModule: ActivitiesModule,
  categoryHighlightModule: TravelGuides,
  subscriptionBannerModule: Subscribe,
  realEstateModule: RealEstate,
  classicsModule: TwoColumnImageContent,
  galleryModule: Gallery,
  currentIssueModule: CurrentIssue,
  nestedFaqModule: NestedFaqModule,
  simpleBanner: SimpleBanner,
  bannerWithBottomContent: BannerWithBottomContent,
  introWithImages: IntroWithImages,
  coverageOverview: CoverageOverview,
  miniGallery: MiniGallery,
  teamMembers: TeamMembers,
  ctaCardsSection: CtaCardSection,
  formContent: DynamicForm,
  contactUsModule: ContactUsComponent,
  shopifyProductListingModule: ShopifyProductListing,
};
